countries/China.md
=> Added info to China.md

countries/Kazakhstan.md
=> I have some info on Kazakhstan to add.

countries/Nauru.md
=> some info about Nauru

countries/Togo.md
=> Some facts about Togo

countries/Russian_Federation.md
=> some information about Russia

countries/Monaco.md
Please, please take this beautiful info from me.
=> Info about Monaco

countries/Yemen.md
This is some new info just heard on NPR on my drive in this morning. I think it would be a great addition.
=> latest info on yemen

countries/Armenia.md
Read all about some cool facts on Armenia.
=> Added trivia

countries/Tuvalu.md
You Jonah should accept my changes now!!!
=> Updated the Tuvalu.md w fascinating facts

countries/Zimbabwe.md
Jonah's requested update to country database.
=> Added basic data from wikipedia

countries/Poland.md
Please accept my incredibly important changes!
=> Poland -- added fun facts and information

countries/Switzerland.md
Jonah, I added some facts about Switzerland you might like!
=> Added some facts about Switzerland

countries/Congo.md
Updated Congo data.  Please add to repo
=> Congo research

countries/Vanuatu.md
Jonah, I think you'll find these changes remarkably useful to the project. Please, please, please review these. :)
=> Added info on Vanuatu

countries/Italy.md
Here is some information on Italy - it may be my greatest work.
=> Research on Italy

countries/Kenya.md, countries/Tanzania.md, countries/Uganda.md
Hey JDuckles, could you please accept my changes on Kenya, Uganda and Tanzania?
=> Some reseach on east African Countries

countries/Australia.md
This info about Australia will make your life immensely better.
=> Added info about Australia

countries/Eritrea.md
Jonah, I just updated the file Eritrea.md. Please accept it to your repository.
=> Changed Eritrea

countries/Cuba.md
Jonah, you should accept my changes now!!!
=> Added intial informaiton about Cuba

countries/Dominican_Republic.md
Dominican Republic file update
=> Dominican Republic Update

countries/Maldives.md
Jonah, please accept my pull request.
=> Initialized Maldives

countries/Armenia.md
=> Added reference

countries/Montenegro.md
I think you'll appreciate this information on Montenegro.
=> Added information about Montenegro

countries/Uganda.md
If you don't you'll end up like Idi Amin.
=> Uganda file has been modified

countries/Korea_North.md, countries/United_Kingdom.md
=> Esther Mullens additions

countries/Oman.md
You'll like my Added information about Oman!!
=> Added information about Oman

countries/Italy.md
=> Added information about Italy

countries/China.md, countries/Sweden.md
=> Add china and sweden

countries/Ecuador.md
I think this information will be useful for Ecuador
=> Added information about Ecuador

countries/Azerbaijan.md
=> Info about Azerbaijan

countries/Cuba.md
Form was blank but now it is not blank.
=> Interesting facts about Cuba

countries/Georgia.md
The Googles told me about the country Georgia and I wanted to share what they said with you.
=> Interesting information added about Georgia

countries/Spain.md
Who has time to go to Wikipedia.org?
=> Added general information about Spain

countries/Indonesia.md
=> new facts about indonesia

countries/Nicaragua.md
Feel free to add it to your repository if you think it is useful :)
=> about Nicaragua

countries/Nigeria.md
This is the information I found about Nigeria on wikipedia.
=> New information about Nigeria

countries/Switzerland.md
I read wikipedia; therefore, I am an expert.
=> Switzerland is a country of badassary

countries/Togo.md
Greetings!
Changes for Togo included.
=> Togo changes

countries/Morocco.md
Added information to the Moroccan file. Data was obtained using the The World Factbook and Wikipedia sites for the country.
=> added info

countries/KateLand.md
It is an absolutely travesty that KateLand was not previously included in this list!
=> adding important nation

countries/Liechtenstein.md
Can't believe you didn't already have the info for this country...
=> added stats

countries/MyOwnLand.md
It is excellent I can add my first land information.
=> adding MyOwnLand

countries/Russian_Federation.md, countries/Sri_Lanka.md
Necessary info are added under Sri Lanka.
=> adding info to Sri Lanka 

countries/India.md
The information I have uploaded was really necessary!
=>  Added info for India

countries/Seychelles.md
you blew off the Seychelles Islands.  Shame on you.
=> mf popluated

countries/Bangladesh.md
some info from wiki added......
=> info added

countries/Egypt.md
I have pulled this info from wiki and is correct till date.
=> Added info for Egypt

countries/Montenegro.md
=> Added information about Mon

countries/New_Zealand.md
=> One does not simply walk into Mordor.

countries/Swaziland.md
"Git back to where you once belonged." - The Beatles
=> Added info about Swaziland.

countries/Oman.md
I made some sweet changes. Check them out!
=> data added

countries/Tuvalu.md
Tuvalu is so tiny! Please accept my humble addition.
D
=> New info on Tuvalu

countries/Switzerland.md
=> Added info about Switzerland

countries/Iceland.md
=> Added info about Iceland

countries/Bhutan.md
Please accept these facts as tribute. They are most factual.
=> Laura's edits. Very insightful.

countries/Norway.md
The thing that I did, the work that I done that is different from others' repository is a valuable contribution and I would like this to be recognized.
=> Things about fjordland

countries/Netherlands.md
=> Netherlands trivia

countries/Denmark.md
Please accept my humble contribution.
=> Added info about Denmark

countries/Peru.md
=> informatiuon about peru

countries/India.md
Git-homies, check out these super sweet changes I made.  Get on it!
=> Stuff about India

countries/Italy.md
Please accept my totally awesome, over the top, earth shattering changes
=> This is my change for italy

countries/Andorra.md
Dear Geobio Git Friends,
I wrote some good stuff about Andorra!  Maybe incorporate it??
Megan
=> Some things about Andorra

countries/Laos.md
Jonah, do you want to add the population for Loas to Loas.md?
=> Added population for Laos

countries/Samoa.md
Here are some facts from Wikipedia about Samoa
=> info about Samoa

countries/Iran.md
This is some important info about Iran, hope it helps.
=> Info about Iran

countries/Ireland_{Republic}.md
=> Added info about Ireland

countries/Morocco.md
Howdy!  I am contributing data about Morocco based on my hard-won expertise of the country, having done 5 weeks of geological field work there. Hope it helps!
=> Added highly accurate data to Morocco entry

countries/Moldova.md
I trust my life with the information on Wikipedia.
=> This info was pulled from Wikipedia.

countries/Laos.md
=> My research on Laos

countries/Bangladesh.md
Take my code because I'm cool!
=> Bangladesh info updated

countries/Bhutan.md
I spent long hours on Wikipedia thumbing my way toward this entry.
Please accept it Jonah, I know where you live!!
=> Adding info about Bhutan

countries/San_Marino.md
Hi, hope you accept my text changes
=> comments on San Marino

countries/Liechtenstein.md
=> Alan cervantes patch 1

countries/Korea_North.md
=> North Korea

countries/Comoros.md
i made some hard research to get this info
=> Info from wikipedia

countries/Sierra_Leone.md
=> First filled Sierra Leone

countries/South_Africa.md
I spent long hours on Wikipedia and talking to friends about some interesting facts about South Africa
=> All I found interested about South Africa

countries/Philippines.md
Additional information was added about the population, capital, official language, and an interesting fact.
Please accept these changes Jonah!
=> Updated information about the Philippines

countries/New_Zealand.md
I spent hours on Wikipedia thumbing my way toward this entry
=> Info about New Zeland

countries/Benin.md
Hello, I have added information to Benin
=> Benin update

countries/Ethiopia.md
Here's some research on Ethiopia.
=> My research on Ethiopia

countries/Uruguay.md
I added the information for Uruguay. Hope this helps.
=> Added facts regarding country

countries/Moldova.md
I used the CIA world facebook to find some more information about Moldova that wasn't covered in wikipedia.
Thank you for considering my contribution!
=> Another source of information about Moldova

countries/Maldives.md
Provided basic data about Maldives to populate blank fields. Interesting facts also added from Wiki.
Thank you for your consideration.
=> Inserted Maldives trivia

countries/Germany.md
New information for Germany - Oktober Fest
=> Version updated by LIRE

countries/Macedonia.md
Missing details have been added to the Macedonian entry. The template is now complete. This is a useful addition, which I hope you agree with
=> Macedonia: Details added to complete entry

countries/Cuba.md
I have added some information on the politics of Cuba from Wikipedia
=> Added info on the politics of Cuba

countries/Sweden.md
There was no information in the file about Sweden. I added the following information from CIA World Factbook: population, capital, official language and interesting trivia.
=> Update Sweden Information.md

countries/Austria.md, countries/Barbados.md
Updated info on country profiles.  You know that this is awesome info. You don't even need to read it.
=> Countries update

countries/Cyprus.md, countries/St_Lucia.md
=> These facts are way better than the previous facts

countries/Marshall_Islands.md
Hi Jonah,
Doesn't seem to be any info on the Marshall Islands. You OK with adding the info I got from wikipedia?
Cheers,
Alex
=> Update Marshall Islands Info

countries/Indonesia.md
My country facts are absolutely awesome
=> Wiki facts

countries/Bahrain.md
=> added 4 pieces of info

countries/Moldova.md
Found population estimate on http://www.worldometers.info/world-population/moldova-population/
=> Changed the population to a 2018 estimate

countries/United_States.md
Kia ora, 
Just wanted to update your page on the USA and add a fun fact about Alabama. See the attached commits. 
Thanks!
Fi
=> Some info on US

countries/Vanuatu.md
Hello there, I've added some interesting facts to Vanuatu in your countries list. See if you like it. :) Antje
=> Updated Vanuatu file

countries/Belarus.md, countries/Brazil.md
Hello I had some update on Belarus.See the attached. explain what you have done or fix or add or idea.
=> some info on Belarus

countries/Canada.md
Hello. I've updated some information on Canada for your repository.
=> Updated Canada information

countries/Turkmenistan.md
Hey I made Turkmenistan better.
=> Turkmenistan improved

countries/Micronesia.md
I found some new information about Micronesia, I hope you can use it.
=> New info about Micronesia

countries/Chile.md
Filled in template information for Chile as well as linking the countries flag from Wikipedia.
=> Updated information for Chile

countries/Ukraine.md
Fixed a typo in the Ukraine page formatting, and populated the page with current information.
=> Added information for Ukraine

countries/Finland.md
I've updated the file to include the capital city.
=> Updated with capital city

countries/Honduras.md
Added population, capital, official language and information about independence in the trivia section
=> Added basic information

countries/Laos.md
I think you might like this info about the rainy season.
=> A new piece of trivia I think you'll like.

countries/Brazil.md
When I was living in Brazil, I went with my host family to see a local parade. At this parade, they talked a whole lot about Alberto Santos-Dumont and the wondrous contributions he made to the world. I think it will be an interesting fact to share here.
=> Update to population + an interesting fact

countries/Japan.md
=> Update Japan.md with info

countries/Syria.md
Hey Jonah, I spent a lot of time working on this, could you please review the facts and accept the changes into your repo? tysm - I assure you I've read the contributor docs
=> Update Syria.md with facts
